const localize = {
  en: {
    homeTitle: "Louis Vuitton x Nike Air Force 1",
    homeDescription:
      "Louis Vuitton x Nike Air Force 1 is the final design of designer Virgil Abloh - Artistic Director of Louis Vuitton's men's fashion brand.",
    homeQuestionSearch: "Which product do you want to search for?",
    loginImportNumberPhone: "Enter your phone number",
    titleVerification: "Enter Auth Code",
    descVerification: "Enter the 6-digit code sent to: +84 $numberPhone",
    questionResetVerification: "Didn't receive the code?",
    descWaittingTimeVerification: `${"Gửi lại"} (${"$waittingTime"}s)`,
    goRegisterVerification: "Đăng ký tài khoản mới",
    continueVerification: "Continue",
    labelNameRegister: "Tên cửa hàng",
    placeholderNameRegister: "Nhập tên cửa hàng",
    codeRegister: "Mã khách hàng VIP",
    placeholdercodeRegister: "Nhập mã khách hàng VIP",
    titleRegister: "Đăng ký",
    descRegister: "Hãy nhập một số thông tin về cửa hàng nào!",
    labelSelectRegister: "Lĩnh vực kinh doanh",
    placeholderSelectRegister: "Chọn lĩnh vực",
    optionalSelectRegister: "(Không bắt buộc)",
    continueRegister: "Tiếp tục",
    desccontactInfoRegister: "Thông tin liên hệ đến shop & địa chỉ shop là?",
    labelUserInfoRegister: "Họ & tên",
    placeholderUserInfoRegister: "Nhập họ & tên",
    labelEmailRegister: "Email",
    placeholderEmailRegister: "Nhập địa chỉ Email",
    labelAddressRegister: "Địa chỉ",
    placeholderAddressRegister: "Địa chỉ đầy đủ",
  },
  vi: {
    placeholderAddressRegister: "Địa chỉ đầy đủ",
    labelAddressRegister: "Địa chỉ",
    placeholderEmailRegister: "Nhập địa chỉ Email",
    labelEmailRegister: "Email",
    placeholderUserInfoRegister: "Nhập họ & tên",
    labelUserInfoRegister: "Họ & tên",
    desccontactInfoRegister: "Thông tin liên hệ đến shop & địa chỉ shop là?",
    continueRegister: "Tiếp tục",
    optionalSelectRegister: "(Không bắt buộc)",
    placeholderSelectRegister: "Chọn lĩnh vực",
    labelSelectRegister: "Lĩnh vực kinh doanh",
    descRegister: "Hãy nhập một số thông tin về cửa hàng nào!",
    titleRegister: "Đăng ký",
    placeholdercodeRegister: "Nhập mã khách hàng VIP",
    codeRegister: "Mã khách hàng VIP",
    placeholderNameRegister: "Nhập tên cửa hàng",
    labelNameRegister: "Tên cửa hàng",
    continueVerification: "Tiếp",
    goRegisterVerification: "Đăng ký tài khoản mới",
    descWaittingTimeVerification: `${"Gửi lại"} (${"$waittingTime"}s)`,
    questionResetVerification: "Bạn không nhận được mã?",
    descVerification: "Nhập mã 6 số được gửi đến: +84 $numberPhone",
    titleVerification: "Nhập mã xác thực",
    loginImportNumberPhone: "Nhập số điện thoại",
    homeQuestionSearch: "Bạn muốn tìm kiếm sản phẩm nào?",
    homeDescription:
      "Louis Vuitton x Nike Air Force 1 là thiết kế cuối cùng của nhà thiết kế Virgil Abloh - Giám đốc nghệ thuật thương hiệu thời trang nam của Louis Vuitton.",
    homeTitle: "Louis Vuitton x Nike Air Force 1",
  },
};

export default localize;
